:root{
  --bg:#0f0f1a;
  --card:#1a1a2e;
  --gold:#c8a96e;
  --text:#eee;
}
body{
  margin:0;
  background:var(--bg);
  color:var(--text);
  font-family:system-ui;
}
.header{
  display:flex;
  justify-content:space-between;
  padding:20px;
  background:#111;
}
.button{
  background:var(--gold);
  border:none;
  padding:8px 14px;
  cursor:pointer;
}
.card{
  background:var(--card);
  padding:16px;
  border-radius:8px;
}
