const crypto = require('crypto');
const { neon } = require('@neondatabase/serverless');

const SESSION_HOURS=+(process.env.SESSION_HOURS||12), OFFLINE=+(process.env.HEARTBEAT_OFFLINE_SECONDS||600);
const OWNER_USER=process.env.OWNER_USER||'owner', OWNER_PASSWORD=process.env.OWNER_PASSWORD||'';
const SECRET=process.env.SESSION_SECRET||'';
const WEBHOOKS={critical:process.env.WEBHOOK_CRITICAL||'',warning:process.env.WEBHOOK_WARNING||'',info:process.env.WEBHOOK_INFO||''};
const now=()=>new Date().toISOString(); const id=(n=16)=>crypto.randomBytes(n).toString('hex');
const mask=v=>{v=String(v||'');return v.length<10?'••••••••':v.slice(0,4)+'••••••••'+v.slice(-4)};
const safeEq=(a,b)=>{a=Buffer.from(String(a));b=Buffer.from(String(b));return a.length===b.length&&crypto.timingSafeEqual(a,b)};
const hashPassword=(p,s=id())=>s+':'+crypto.scryptSync(p,s,64).toString('hex');
const checkPassword=(p,h)=>{try{let[s,x]=h.split(':');return safeEq(x,crypto.scryptSync(p,s,64).toString('hex'))}catch{return false}};
const b64u=x=>Buffer.from(x).toString('base64url');
function token(payload){let p=b64u(JSON.stringify(payload)),sig=crypto.createHmac('sha256',SECRET).update(p).digest('base64url');return p+'.'+sig}
function verifyToken(t){try{let[p,s]=String(t||'').split('.');let ex=crypto.createHmac('sha256',SECRET).update(p).digest('base64url');if(!safeEq(s,ex))return null;let d=JSON.parse(Buffer.from(p,'base64url'));return d.exp>Date.now()?d:null}catch{return null}}
function b32decode(s){let A='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567',bits='';for(let c of String(s).replace(/=|\s/g,'').toUpperCase()){let v=A.indexOf(c);if(v>=0)bits+=v.toString(2).padStart(5,'0')}let out=[];for(let i=0;i+8<=bits.length;i+=8)out.push(parseInt(bits.slice(i,i+8),2));return Buffer.from(out)}
function totp(secret,code){if(!secret)return true;let key=b32decode(secret),ctr=Math.floor(Date.now()/30000);for(let d=-1;d<=1;d++){let b=Buffer.alloc(8);b.writeBigUInt64BE(BigInt(ctr+d));let h=crypto.createHmac('sha1',key).update(b).digest(),o=h[19]&15,n=(h.readUInt32BE(o)&0x7fffffff)%1000000;if(safeEq(String(n).padStart(6,'0'),String(code||'')))return true}return false}
const resp=(status,body,headers={})=>({statusCode:status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff','x-frame-options':'DENY','referrer-policy':'no-referrer',...headers},body:JSON.stringify(body)});
function clientIp(e){return String(e.headers['x-nf-client-connection-ip']||e.headers['x-forwarded-for']||'').split(',')[0].trim()}
function parse(e){try{return JSON.parse(e.body||'{}')}catch{return {}}}
function cookies(e){let c=e.headers.cookie||'';return Object.fromEntries(c.split(';').map(x=>x.trim().split(/=(.*)/s).slice(0,2)).filter(x=>x[0]))}
function can(a,role){return a&&(a.role==='owner'||a.role===role||(a.role==='admin'&&role==='viewer'))}
let initialized=false;
async function store(){if(!process.env.DATABASE_URL)throw Error('DATABASE_URL missing');let sql=neon(process.env.DATABASE_URL);if(!initialized){await sql`CREATE TABLE IF NOT EXISTS rice_protect_state (id integer PRIMARY KEY, data jsonb NOT NULL, updated_at timestamptz NOT NULL DEFAULT now())`;let rows=await sql`SELECT id FROM rice_protect_state WHERE id=1`;if(!rows.length){let d={licenses:{},servers:{},events:[],players:{},admins:{},commands:{},settings:{version:'4.0.0'}};await sql`INSERT INTO rice_protect_state(id,data) VALUES(1,${JSON.stringify(d)}::jsonb)`}initialized=true}return sql}
async function load(sql){let r=await sql`SELECT data FROM rice_protect_state WHERE id=1`;let d=r[0].data;d.licenses||={};d.servers||={};d.events||=[];d.players||={};d.admins||={};d.commands||={};d.settings||={version:'4.0.0'};return d}
async function save(sql,d){await sql`UPDATE rice_protect_state SET data=${JSON.stringify(d)}::jsonb, updated_at=now() WHERE id=1`}
async function addEvent(d,type,severity,data={}){let e={id:id(8),time:now(),type,severity,...data};d.events.unshift(e);d.events=d.events.slice(0,5000);let u=WEBHOOKS[severity];if(u)fetch(u,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username:'Rice Protect',content:`[${severity.toUpperCase()}] ${type}\n${JSON.stringify(data).slice(0,1500)}`})}).catch(()=>{});return e}
function cleanLicense(x,key){let y={...x,key,maskedKey:mask(key),serverLicenseMasked:mask(x.serverLicense)};delete y.serverLicense;return y}
exports.handler=async e=>{try{
 if(!SECRET||SECRET.length<32||!OWNER_PASSWORD)return resp(500,{error:'server-not-configured'});
 let sql=await store(),d=await load(sql),p=e.path.replace(/^\/\.netlify\/functions\/api/,'')||'/',m=e.httpMethod,b=parse(e),remote=clientIp(e);
 if(!d.admins[OWNER_USER]){d.admins[OWNER_USER]={username:OWNER_USER,password:hashPassword(OWNER_PASSWORD),role:'owner',totpSecret:'',createdAt:now()};await save(sql,d)}
 if(m==='POST'&&p==='/v1/heartbeat'){let key=String(b.key||''),l=d.licenses[key];if(!l||l.revoked||l.blocked){await addEvent(d,'Unauthorized License','critical',{license:mask(key),ip:remote,serverName:b.serverName||''});await save(sql,d);return resp(200,{valid:false,reason:'invalid-or-blocked'})}if(l.expiresAt&&Date.parse(l.expiresAt)<Date.now()){await addEvent(d,'Expired License','warning',{license:mask(key),serverName:b.serverName||''});await save(sql,d);return resp(200,{valid:false,reason:'expired'})}let sl=String(b.serverLicense||'');if(l.serverLicense&&!safeEq(l.serverLicense,sl)){await addEvent(d,'License Binding Mismatch','critical',{license:mask(key),serverName:b.serverName||'',ip:remote});await save(sql,d);return resp(200,{valid:false,reason:'server-binding-mismatch'})}let sid=l.serverId||(l.serverId=id(8)),s=d.servers[sid]||{id:sid,createdAt:now(),connections:[]};Object.assign(s,{name:String(b.serverName||'Unknown'),ip:remote,endpoint:String(b.endpoint||''),framework:String(b.framework||'unknown'),protectVersion:String(b.protectVersion||'unknown'),playerCount:+b.playerCount||0,maxPlayers:+b.maxPlayers||0,resources:Array.isArray(b.resources)?b.resources.slice(0,250):[],lastHeartbeat:now(),licenseKey:key,status:'online'});s.connections.unshift({time:now(),ip:remote});s.connections=s.connections.slice(0,50);d.servers[sid]=s;l.lastSeen=now();l.serverName=s.name;l.lastIp=remote;let cmds=(d.commands[sid]||[]).filter(c=>!c.deliveredAt).map(c=>{c.deliveredAt=now();return{id:c.id,action:c.action,resource:c.resource,settings:c.settings}});await save(sql,d);return resp(200,{valid:true,product:l.product,expiresAt:l.expiresAt||null,serverId:sid,commands:cmds})}
 if(m==='POST'&&p==='/v1/event'){let l=d.licenses[String(b.key||'')];if(!l||l.revoked||l.blocked)return resp(401,{error:'unauthorized'});await addEvent(d,String(b.type||'Security Event'),['critical','warning','info'].includes(b.severity)?b.severity:'info',{serverId:l.serverId,serverName:b.serverName||l.serverName||'',resource:b.resource||'',details:String(b.details||'').slice(0,2000),player:b.player||null});await save(sql,d);return resp(200,{ok:true})}
 if(m==='POST'&&p==='/v1/player'){let l=d.licenses[String(b.key||'')];if(!l||l.revoked||l.blocked)return resp(401,{error:'unauthorized'});let k=(l.serverId||'x')+':'+String(b.sessionId||id(6));let cp={...b};delete cp.key;d.players[k]={...cp,serverId:l.serverId,updatedAt:now()};await addEvent(d,b.action==='leave'?'Player Left':'Player Joined','info',{serverId:l.serverId,serverName:l.serverName||'',player:{name:b.name,serverId:b.serverPlayerId,discord:b.discord,fivem:b.fivem,license:b.license,steam:b.steam,ip:b.ip},details:b.reason||''});await save(sql,d);return resp(200,{ok:true})}
 if(m==='POST'&&p==='/api/login'){let a=d.admins[String(b.username||'')];if(!a||!checkPassword(String(b.password||''),a.password)||!totp(a.totpSecret,b.code)){await addEvent(d,'Admin Login Failed','warning',{username:b.username||'',ip:remote});await save(sql,d);return resp(401,{error:'invalid-login'})}let t=token({username:a.username,role:a.role,exp:Date.now()+SESSION_HOURS*3600000});await addEvent(d,'Admin Login','info',{username:a.username,ip:remote});await save(sql,d);return resp(200,{ok:true,role:a.role},{'set-cookie':`rp_session=${t}; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=${SESSION_HOURS*3600}`})}
 if(m==='POST'&&p==='/api/logout')return resp(200,{ok:true},{'set-cookie':'rp_session=; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=0'});
 let a=verifyToken(cookies(e).rp_session);if(p.startsWith('/api/')&&!a)return resp(401,{error:'login-required'});
 if(m==='GET'&&p==='/api/me')return resp(200,a);
 if(m==='GET'&&p==='/api/dashboard'){for(let s of Object.values(d.servers))s.status=(Date.now()-Date.parse(s.lastHeartbeat||0)<OFFLINE*1000)?'online':'offline';return resp(200,{licenses:Object.entries(d.licenses).map(([k,v])=>cleanLicense(v,k)),servers:Object.values(d.servers).map(s=>({...s,licenseKey:mask(s.licenseKey)})),events:d.events.slice(0,250),players:Object.values(d.players).slice(-500),admins:can(a,'owner')?Object.values(d.admins).map(x=>({username:x.username,role:x.role,twoFactor:!!x.totpSecret,createdAt:x.createdAt})):[],version:d.settings.version})}
 if(m==='POST'&&p==='/api/licenses'){if(!can(a,'admin'))return resp(403,{error:'forbidden'});let key='RICE-'+crypto.randomBytes(16).toString('hex').toUpperCase();d.licenses[key]={product:String(b.product||'Rice Protect Ultimate'),serverLicense:String(b.serverLicense||''),expiresAt:b.expiresAt||null,blocked:false,revoked:false,createdAt:now(),note:String(b.note||'')};await addEvent(d,'License Created','info',{admin:a.username,license:mask(key)});await save(sql,d);return resp(201,{key})}
 let lm=p.match(/^\/api\/licenses\/([^/]+)\/(block|unblock|revoke|extend|rebind)$/);if(m==='POST'&&lm){if(!can(a,'admin'))return resp(403,{error:'forbidden'});let key=decodeURIComponent(lm[1]),l=d.licenses[key];if(!l)return resp(404,{error:'not-found'});let act=lm[2];if(act==='block')l.blocked=true;if(act==='unblock'){l.blocked=false;l.revoked=false}if(act==='revoke')l.revoked=true;if(act==='extend')l.expiresAt=b.expiresAt||null;if(act==='rebind')l.serverLicense=String(b.serverLicense||'');await addEvent(d,'License '+act,'warning',{admin:a.username,license:mask(key)});await save(sql,d);return resp(200,{ok:true})}
 let cm=p.match(/^\/api\/servers\/([^/]+)\/command$/);if(m==='POST'&&cm){if(!can(a,'admin'))return resp(403,{error:'forbidden'});let sid=cm[1],s=d.servers[sid];if(!s)return resp(404,{error:'not-found'});let allowed=['disable_resource','enable_resource','update_settings'];if(!allowed.includes(b.action))return resp(400,{error:'bad-action'});let resource=String(b.resource||'');if(resource&&!(s.resources||[]).some(r=>(typeof r==='string'?r:r.name)===resource))return resp(400,{error:'resource-not-protected'});(d.commands[sid]||=[]).push({id:id(8),action:b.action,resource,settings:b.settings||{},createdAt:now(),admin:a.username});await addEvent(d,'Remote Command Queued','critical',{admin:a.username,serverId:sid,serverName:s.name,details:b.action+' '+resource});await save(sql,d);return resp(200,{ok:true})}
 if(m==='POST'&&p==='/api/admins'){if(!can(a,'owner'))return resp(403,{error:'forbidden'});let u=String(b.username||'').trim();if(!u||d.admins[u]||!['owner','admin','viewer'].includes(b.role)||String(b.password||'').length<10)return resp(400,{error:'invalid'});d.admins[u]={username:u,password:hashPassword(String(b.password)),role:b.role,totpSecret:String(b.totpSecret||''),createdAt:now()};await addEvent(d,'Admin Created','warning',{admin:a.username,target:u,role:b.role});await save(sql,d);return resp(201,{ok:true})}
 if(m==='GET'&&p==='/health')return resp(200,{ok:true,time:now()});return resp(404,{error:'not-found'});
 }catch(err){console.error(err);return resp(500,{error:'server-error'})}}
